### ISSUE TITLE
Add accounts endpoint

### ISSUE THREAD

**Issue by djreimer** [DripEmail/drip-ruby#14]

**Comment by edavis10** [comment]
I could use this for an app I'm working on. Drip OAuth is working but I need to get a list of accounts a client has before I can make any additional API calls.

**Comment by djreimer** [comment]
:+1: will get this pushed out shortly

**Comment by edavis10** [comment]
Let me know if you need a second set of eyes, a beta test, or code review.

**Comment by djreimer** [comment]
Just cut a new version with a few new endpoints, this one included: https://github.com/DripEmail/drip-ruby/releases/tag/v0.0.4

**Comment by edavis10** [comment]
I just tested it with an oauth account and `#accounts` worked exactly as I expected. Thanks.

**Comment by djreimer** [comment]
:tada:
