### ISSUE TITLE
Can't get Drip connection to work

### ISSUE THREAD

**Issue by ldestrooper** [DripEmail/drip-ruby#35]
I'm just starting with Drip, and it's my first time to integrate email, so very new at this.

I'm trying to make a simple opt-in that sends out an email campaign but the Drip::Client doesn't seem to be recognized.

The error i'm getting is this:
`NameError (uninitialized constant MailController::Drip):`

and this is my code for now:

In gemfile:
`gem 'drip-ruby', require: 'drip'`

In mailcontroller:
```
class MailController < ApplicationController

	def send_pro_bundle
		# Connect to API
		client = Drip::Client.new do |config|
			config.api_key = Rails.application.secrets.drip_api_key
			config.account_id = Rails.application.secrets.drip_account_key
		end

		# Fetch & setup variables
		email = params[:email]
		fname = params[:fname]
		lname = params[:lname]

		options = {
			time_zone: Time.zone.name,
			custom_fields: {
				first_name: fname,
				last_name: lname
			}
		}

		# Create or update contact
		response = client.create_or_update_subscriber(email, options)

		if response.success?
			puts response.body["subscribers"]
		end

		# Send email
	end
end
```

What am i doing wrong? (And my apologies in advance for this newbie question.)

**Comment by djreimer** [comment]
Hmm have you tried `bundle install` to ensure the gem was actually installed after adding to the Gemfile (and restarting your Rails server)?

If that's not the issue, I would try adding `require 'drip'` to the top of your file to see if that helps. That shouldn't be necessary since it is being required in the Gemfile explicitly, but worth a shot.

**Comment by ldestrooper** [comment]
Thanks @djreimer for the fast reply! Forgot to reset my server, my apologies and thanks again!

**Comment by djreimer** [comment]
👍 🌟
