### ISSUE TITLE
undefined method `subscribers' for #<Drip::Response:

### ISSUE THREAD

**Issue by kivanio** [DripEmail/drip-ruby#48]
Upgrade to 3.x

<code>
    @last_response = client.subscriber(user.email)
    return false unless @last_response.success?
    subscriber = @last_response.subscribers.first
</code>

**Comment by jonbuda** [comment]
Similar but for `accounts` and `campaign`. it doesn't seem like the response JSON is being parsed properly. Using gem v3.1.0 and Ruby 2.5.1

**Comment by will-in-wi** [comment]
I see the issue, and am working on a fix…

**Comment by jonbuda** [comment]
@will-in-wi excellent! thanks for the super quick turn-around!
