### ISSUE TITLE
Drip Gem Doesn't Support New Shopper Activity API

### ISSUE THREAD

**Issue by HunterHillegas** [DripEmail/drip-ruby#55]
The new APIs here:

https://headwayapp.co/drip-ecrm-release-notes/drip-s-new-shopper-activity-api-is-here!-92779

Are not included in the Drip Ruby gem.

**Comment by bfortune347** [comment]
Hey Hunter, 

You are right! We're currently focused on expanding out the Shopper Activity API's capabilities before fleshing them out in our Ruby gem (or other clients). Our strategy is to enable more functionality before making that functionality easier to work with. That said, we're always interested in hearing from customers interested in this kind of thing, as it does influence our prioritization. Thanks for creating the issue. 

-Brendan Fortune
Sr. Director of Product @ Drip

**Comment by HunterHillegas** [comment]
Hi @bfortune347,

Gotcha. FWIW, our app Drip integration is entirely based on the gem so for new API features that don't have corresponding gem updates, that either means we don't adopt the feature or we consider forking the gem and adding support, which while me might consider doing, isn't super likely.

Cheers,
Hunter

**Comment by bfortune347** [comment]
@HunterHillegas - makes sense, and appreciate the feedback. 👍

**Comment by caseygipson** [comment]
I'll echo @HunterHillegas , I just recently signed up and was excited about this newer order endpoint with triggering capabilities and it's definitely a bummer that it isn't supported in the ruby gem.

Any sort of timeline on when we might see an update for this? 

Thanks,
-Casey

**Comment by bfortune347** [comment]
No update yet, though we have no immediate plans for extra Shopper Activity endpoints at present, which means the discussion about when to extend support is top-of-mind. 

There will be some internal priority discussions in the next few weeks, so should have updates at that point.

**Comment by caseygipson** [comment]
Awesome, thanks @bfortune347 !

**Comment by jmartyniak** [comment]
If we are voting on adding Shopper Activity end points to gem, I would +1 that.

Just signed up for drip, and one of the reasons that we did was because of the new shopper activity end points.

**Comment by will-in-wi** [comment]
Hey all, I've been working on shopper activity support in https://github.com/DripEmail/drip-ruby/pull/59

Feel free to test this out and provide feedback. I'm hoping to get this merged and released in the next week or so, depending on other priorities.

**Comment by will-in-wi** [comment]
I just merged the new API to master. I'm going to keep this issue open until I do a stable release, hopefully tomorrow. Feel free to play with master.

**Comment by will-in-wi** [comment]
Version 3.3.0 is out!
