### ISSUE TITLE
Plan to support fetch current user endpoint?

### ISSUE THREAD

**Issue by erinzobitz** [DripEmail/drip-ruby#69]
Currently, there is no Ruby support for this endpoint: https://developer.drip.com/?ruby#users

Is there a plan to implement it in the future?

**Comment by will-in-wi** [comment]
No immediate plans, although I will add a ticket for it. We would be willing to accept a PR if you wanted to tackle it!

**Comment by tiannaavery** [comment]
@erinzobitz Thanks for pointing this out to us, and thanks for your patience! Version 3.4.0 should have this feature. :)
