### ISSUE TITLE
Failed to add/update order to Drip.

### ISSUE THREAD

**Issue by ldestrooper** [DripEmail/drip-ruby#75]
Since a few weeks Drip is no longer updating somehow and this is the error i am receiving, can you help me out how to fix this?
`2021-01-26T09:23:25.527213+00:00 app[web.1]: Failed to add/update order to Drip.
2021-01-26T09:23:25.527235+00:00 app[web.1]: {"validation_errors"=>[{"keyword"=>"format", "dataPath"=>".items[0].product_url", "schemaPath"=>"order_item.json/properties/product_url/format", "params"=>{"format"=>"uri"}, "message"=>"should match format \"uri\""}]}`

**Comment by will-in-wi** [comment]
Could you post the value you are sending in the `product_url` field?

**Comment by ldestrooper** [comment]
This is the value that is sent: "/koffie/proefpakket-koffie"

**Comment by will-in-wi** [comment]
The value presently must be an [RFC 3986 URI](https://tools.ietf.org/html/rfc3986#section-1.1.2). So it needs the scheme and domain as part of the string.

The reason for this is that often we will link to your product in an email or other communication. Without the full URI, we can't actually do this.

If it is helpful, behind the scenes, we use a JSON Schema document to define the format. This string is defined as `"format":"uri"`, which is defined here: https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers

**Comment by will-in-wi** [comment]
I'm going to close this, but if you have further questions, just reply and I'll re-open the ticket. Thanks for using Drip!

**Comment by ldestrooper** [comment]
Thank you! It works now 🙏
